/* ============================================================
   机器人产业链 · 竞争格局 · 国产替代 · 真理文件（信源内联）
   ------------------------------------------------------------
   这份文件即真理：HTML 从它渲染，无财务硬数据、无投资建议。
   - segments : 环节（三层 down/mid/up）
   - companies: 公司节点，可挂多环节；每家自带 source / source_type / confidence
   - edges    : 仅股权/供应等非显然关系；竞争关系由「同环节成员」前端自动派生
   口径：定性梯队（head/waist/startup），不过期。
   来源：codex 联网核实 2026-07（8 个上游环节）；下/中游骨架待补。
   ============================================================ */
window.GRAPH = {
  meta: { title: "机器人产业链 · 竞争格局 · 国产替代", as_of: "2026-07",
    note: "定性竞争格局图，无财务数字与投资建议；信源以各节点 source 字段为准。" },

  segments: [
    { id:"humanoid", layer:"down", name:"人形整机", def:"通用人形机器人本体厂商——需求侧，决定上游谁吃肉。" },
    { id:"service", layer:"down", name:"服务 / 专用机器人", def:"清洁、巡检、配送等专用形态整机。" },
    { id:"joint", layer:"mid", name:"关节模组总成", def:"把减速器 + 电机 + 编码器 + 驱动集成为一体化关节。" },
    { id:"bodyint", layer:"mid", name:"本体 / 系统集成", def:"整机结构、运动控制与系统集成。" },
    { id:"harmonic", layer:"up", name:"谐波减速器", def:"以波发生器、柔轮、刚轮弹性啮合实现高减速比、低背隙、高定位精度的小型精密传动部件，主要用于机器人小负载高精度关节。", bottleneck:"柔轮疲劳寿命与材料/热处理、齿形设计与传动误差控制、超薄壁高精度加工与检测设备、交叉滚子轴承、批量一致性；国产替代看点=从「能用」到「长寿命高精度批量稳定供货」并进入人形关节模组客户验证。",
      invest:{ as_of:"2026-07",
        dims:[
          {k:"单机价值量",v:"高",tone:"hi",flag:"待锚",note:"人形旋转关节（肩肘腕等小负载高精度）主力减速方案，单机多关节用量大；精确 BOM 占比无一手源，标待锚。"},
          {k:"国产化空间",v:"中·收窄",tone:"mid",note:"国产已出真龙头——绿的谐波官网口径国内市占 60%+（⚠ 官网非第三方）、来福谐波紧随；替代逻辑已部分兑现，剩余空间在高端寿命/一致性对标哈默纳科。空间比丝杠小但确定性高。"},
          {k:"竞争格局",v:"较集中·龙头可辨",tone:"hi",note:"国产双头（绿的/来福）清晰，中大力德/双环为腰部配套；比丝杠 6 家混战清爽。"},
          {k:"技术壁垒",v:"高",tone:"hi",note:"柔轮疲劳寿命、材料热处理、齿形设计、超薄壁加工、批量一致性，卡点深，但国产头部已越过“能用”门槛。"}
        ],
        verdict:"国产替代已兑现、龙头明确的确定性环节：人形放量的 beta ＋ 龙头集中度带来的 alpha 都相对可辨，相较丝杠属“选手已定、赛道待放量”。主要看人形放量节奏。",
        top_pick:"绿的谐波（688017.SH）国产谐波第一主线，市占领先、产品线延伸无框电机/关节；来福谐波（3952.HK）第二主线。",
        risks:"估值已 price-in 替代预期 / 人形放量不及预期 / 海外降价；⚠ 市占率为官网口径未经第三方核实。" } },
    { id:"rv", layer:"up", name:"RV 减速器", def:"RV减速器是以摆线针轮少齿差传动和多级支撑结构实现高扭矩、高刚性、高精度输出的精密减速器，主要用于工业机器人及人形机器人的大负载关节，如肩、肘、腰、髋等。", bottleneck:"核心卡点在摆线轮齿形设计与修形、针齿壳/行星架/轴承等高精密加工、热处理与材料一致性、装配预紧和批量寿命稳定性；国产替代看点是从能做样机走向高一致性量产、进入机器人本体厂批量验证并压低成本。" },
    { id:"screw", layer:"up", name:"行星滚柱丝杠", def:"行星滚柱丝杠是将电机旋转运动高效率转换为高载荷、高刚性、高寿命直线运动的精密传动副，是人形机器人线性关节/电动缸的核心传动件。", bottleneck:"卡点在小直径高载荷设计、螺纹滚道磨削/滚压成形、滚柱与螺母一致性、热处理与材料疲劳寿命、预紧与回差控制、批量检测设备及良率；国产替代看点是从样件验证走向机器人客户定点和规模化交付。公开一手资料未确认有份量的中外合资专门玩家，未为凑数纳入弱源JV。",
      invest:{ as_of:"2026-07",
        dims:[
          {k:"单机价值量",v:"高",tone:"hi",flag:"待锚",note:"人形线性关节/电动缸核心传动件，单机用量随线性执行器数量走；精确 BOM 占比无一手源，标待锚不写死。"},
          {k:"国产化空间",v:"大",tone:"hi",note:"6 国产 / 2 海外，但国产多在样件验证走向客户定点，量产一致性未兑现，Ewellix/SKF、Rollvis 仍是标杆。空间大＝兑现风险也大。"},
          {k:"竞争格局",v:"分散·未固化",tone:"lo",note:"6 家国产 head 混战（秦川机床/恒立液压/贝斯特都在卡位），真龙头未定。"},
          {k:"技术壁垒",v:"高",tone:"hi",note:"小直径高载荷、螺纹磨削/滚压成形、滚柱一致性、疲劳寿命、良率，卡点密集。"}
        ],
        verdict:"赛道确定、选手未定的高弹性 beta ＋ 未决 alpha 环节：人形放量最直接受益的传动件之一，但谁先过客户定点决定谁吃肉，当前 6 家无一兑现——适合一篮子跟踪，不宜单押。",
        top_pick:"暂不单点。恒立液压（液压精密制造迁移）/ 秦川机床（母机＋丝杠双卡位）是两条最值得跟踪主线。",
        risks:"客户定点落空 / 海外降价 / 良率爬坡慢；⚠ 均未见第三方确认的人形定点放量。" } },
    { id:"frameless", layer:"up", name:"无框力矩电机", def:"用于机器人关节模组的无机壳、直驱/准直驱高扭矩密度电机，通常作为一体化关节执行器的动力源，与减速器、编码器、驱动器、制动器等集成。", bottleneck:"卡点在高牌号钕铁硼与磁路设计、低齿槽转矩/低转矩脉动绕组方案、高槽满率定子工艺、薄壁大中空同轴精度、散热与绝缘可靠性、批量一致性及机器人客户长周期验证；国产替代看点是由通用伺服向人形机器人定制无框电机和关节模组平台化升级。" },
    { id:"coreless", layer:"up", name:"空心杯电机", def:"面向灵巧手、末端执行器、微型关节等小体积高动态场景的无铁芯转子微特电机，核心价值是低惯量、高转速、高功率密度和快速响应。", bottleneck:"卡点在杯形绕组自承结构成型、微米级同轴/动平衡、稀土磁钢与薄壁材料一致性、自动绕线和装配设备、散热与寿命可靠性；国产替代看点是从消费/医疗微电机能力迁移到机器人灵巧手，并缩小与Maxon/Faulhaber在效率、寿命、批量一致性上的差距。" },
    { id:"encoder", layer:"up", name:"编码器", def:"用于机器人关节电机/减速器输出端的角位置、速度与方向反馈部件，常见路线包括光电、磁、电感/旋变及绝对值/增量式编码器，直接影响关节闭环控制精度、动态响应和可靠性。", bottleneck:"卡点在高精度码盘/光栅与读头、磁栅一致性、轴系装调偏心误差补偿、抗振抗温漂、低延迟通信协议、薄型中空结构和批量标定工艺；国产替代看点是从中低端增量式向高分辨率绝对值、关节内置薄型化和高端光电/磁编码器突破。" },
    { id:"fts", layer:"up", name:"六维力 / 触觉传感器", def:"安装在机器人腕部、踝部、关节或灵巧手指/掌面的多轴力觉与触觉感知器件，用于测量三向力、三向力矩或接触压力分布，支撑力控装配、平衡控制、碰撞检测和灵巧操作。", bottleneck:"核心卡点在弹性体结构设计与加工、应变/压阻/电容等敏感材料一致性、温漂与轴间串扰补偿、六维解耦标定、微型化封装、批量一致性和机器人控制器实时通信；国产替代看点是从工业称重/测力向机器人六轴力、关节力矩和触觉阵列迁移，价格与交付可替代海外ATI等，但高精度、低漂移、可靠性和规模化标定仍需验证；未找到可一手确认且足量的独立合资类六维力/触觉传感器厂商，合资形态更多在机器人本体或系统集成侧，未纳入玩家清单。" },
    { id:"hand", layer:"up", name:"灵巧手", def:"安装在人形机器人/机械臂末端、集成多指多自由度执行机构、传动、力/触觉传感与控制接口的末端执行器总成，区别于传统二指夹爪，核心分水岭是自由度、力控精度、触觉集成度和可量产成本。", bottleneck:"卡点在微型高功率密度执行器/空心杯电机、丝杠/齿轮/腱绳等微传动寿命与回差控制、柔性触觉阵列耐久性与标定、轻量化结构材料、手内布线散热、整手装配一致性，以及从“能抓”到“可学习精细操作”的数据与控制闭环；国产替代看点是把Shadow/Allegro级研究型灵巧手降本到可规模交付。",
      invest:{ as_of:"2026-07",
        dims:[
          {k:"单机价值量",v:"高",tone:"hi",flag:"待锚",note:"人形末端执行器，决定“能不能干活”的操作能力，单机 2 只、技术含量高；方案未定型价格波动大，精确占比待锚。"},
          {k:"国产化空间",v:"大",tone:"hi",note:"海外 Shadow/Wonik 是研究级标杆但昂贵，国产因时/灵心巧手在降本量产上卡位；整体处早期，空间大但需求尚未放量。"},
          {k:"竞争格局",v:"分散·早期",tone:"lo",note:"国产头部＋初创并存（无际 startup、强脑 waist），技术路线（腱绳/连杆/直驱、触觉集成度）未收敛，格局远未固化。"},
          {k:"技术壁垒",v:"高·多维",tone:"hi",note:"微型执行器/空心杯、微传动寿命回差、柔性触觉阵列耐久标定、手内布线散热，加上“从能抓到可学习精细操作”的数据控制闭环；壁垒跨机电＋数据两层，最深。"}
        ],
        verdict:"前沿高壁垒、路线未收敛的早期环节：想象空间最大（决定人形能否干活），但技术路线、量产成本、需求节奏三重未知——主题弹性大、证伪风险高，适合跟踪路线收敛信号（触觉标准化/成本曲线）而非早下注。",
        top_pick:"暂不单点。因时机器人（微型伺服自研一体化）/ 灵心巧手（灵巧手专精）是国产两条主线；均处早期，一级色彩重于二级可投。",
        risks:"技术路线被颠覆 / 需求放量遥遥无期 / 初创现金流；⚠ 量产与定点均未兑现。" } },
  ],

  companies: [
    { id:"hds", name:"哈默纳科 Harmonic Drive", segments:["harmonic"],
      origin:"overseas", listed:{ status:"listed", code:"6324.T" }, tier:"head",
      one_liner:"全球谐波减速器原始龙头（含日本 Harmonic Drive Systems、美国 LLC、欧洲 SE 三地主体），提供 HarmonicDrive 减速器、执行器与精密运动控制部件。",
      position:"海外技术标杆与高端份额锚，国产替代主要对标其精度、寿命、可靠性与批量一致性。",
      source_type:"primary", confidence:"high",
      source:"Harmonic Drive Systems IR: https://www.hds.co.jp/english/ir/library/ ；产品页 https://www.harmonicdrive.net/products/gear-units" },
    { id:"nidec", name:"日本电产传动 Nidec Drive", segments:["harmonic"],
      origin:"overseas", listed:{ status:"subsidiary", code:"6594.T" }, tier:"waist",
      one_liner:"日本电产旗下传动部件企业（原 Nidec-Shimpo），产品覆盖行星、摆线与 strain-wave 类精密减速器。",
      position:"海外多品类精密传动竞争者，非谐波绝对龙头，但在运动控制客户与电机协同上有体系优势。",
      source_type:"secondary", confidence:"medium",
      source:"Nidec-Shimpo 资料：https://en.wikipedia.org/wiki/Nidec-Shimpo_America_Corporation" },
    { id:"lvdi", name:"绿的谐波 Leaderdrive", segments:["harmonic"],
      origin:"domestic", listed:{ status:"listed", code:"688017.SH" }, tier:"head",
      one_liner:"国产谐波减速器龙头，研发生产机器人用高性能应变波减速器、旋转执行器、无框力矩电机与转台。",
      position:"国产替代主线核心标的；官网披露国内市占率 60%+、产品定位对标海外龙头，是人形机器人谐波环节最直接受益者。",
      source_type:"primary", confidence:"high",
      source:"绿的谐波官网 https://www.leaderdrive.com/（市占率 60%+ 为官网口径，非独立第三方核实）" },
    { id:"laifu", name:"来福谐波 Laifual", segments:["harmonic"],
      origin:"domestic", listed:{ status:"listed", code:"3952.HK" }, tier:"head",
      one_liner:"中国机器人精密传动核心部件供应商，产品覆盖谐波减速器、关节模组、机械臂及自动化工作站。",
      position:"国产头部第二梯队向第一梯队冲击者；公开披露 2025 年谐波定位精度 ±15 角秒、寿命超 10000 小时，重点服务工业与人形机器人。",
      source_type:"primary", confidence:"high",
      source:"来福谐波官网 https://www.laifual.com/" },
    { id:"zdld", name:"中大力德", segments:["harmonic", "rv"],
      origin:"domestic", listed:{ status:"listed", code:"002896.SZ" }, tier:"waist",
      one_liner:"机电自动化传动企业，机器人减速器产品线含摆线针轮精密减速器与谐波减速器。",
      position:"国产腰部综合传动玩家，优势在电机/驱动/减速器一体化配套；谐波业务体量与高端验证弱于绿的谐波、来福谐波。",
      source_type:"primary", confidence:"high",
      source:"中大力德官网 https://www.zd-motor.com/product/谐波减速器-53" },
    { id:"shuanghuan", name:"双环传动", segments:["harmonic", "rv"],
      origin:"domestic", listed:{ status:"listed", code:"002472.SZ" }, tier:"waist",
      one_liner:"精密齿轮及传动组件龙头，机器人自动化为其驱动/传动应用场景之一，具备精密齿轮加工与传动系统制造平台。",
      position:"机器人精密传动横向玩家；官网可验证其齿轮/组件与机器人自动化能力，作为国产替代链条中的加工/延伸平台看待。",
      source_type:"primary", confidence:"medium",
      source:"双环传动官网 https://www.gearsnet.com/" },
    { id:"jp6268", name:"纳博特斯克 Nabtesco", segments:["rv"],
      origin:"overseas", listed:{ status:"listed", code:"6268.T" }, tier:"head",
      one_liner:"全球RV精密减速器标杆企业，产品面向工业机器人关节、机床转台和自动化设备。",
      position:"海外绝对龙头和技术/寿命/批量一致性标杆，国产厂商主要对标其RV-E、RV-C等系列。",
      source_type:"primary", confidence:"high",
      source:"Nabtesco官网Precision Reduction Gear产品页及Nabtesco FY2025/FY2026 IR资料。" },
    { id:"jp6302", name:"住友重机械 Sumitomo Heavy Industries / Sumitomo Drive", segments:["rv"],
      origin:"overseas", listed:{ status:"listed", code:"6302.T" }, tier:"head",
      one_liner:"提供Fine Cyclo等摆线精密控制减速器，覆盖机器人、半导体和自动化定位场景。",
      position:"海外摆线减速器强势玩家，虽非Nabtesco RV品牌体系，但在高精密摆线传动上构成重要海外竞品。",
      source_type:"primary", confidence:"high",
      source:"Sumitomo Drive Technologies官网Fine Cyclo precision control reducers产品页。" },
    { id:"u03", name:"上海纳博特斯克传动设备有限公司", segments:["rv"],
      origin:"jv", listed:{ status:"subsidiary", code:"" }, tier:"head",
      one_liner:"纳博特斯克在华精密减速器合资平台，面向中国机器人和自动化市场销售/服务RV减速器。",
      position:"本质是海外龙头本土化供给，不属于国产替代，但直接定义国内高端RV价格、交付和质量基准。",
      source_type:"primary", confidence:"high",
      source:"上海机电股份有限公司年报披露的与Nabtesco合资经营精密减速器业务信息。" },
    { id:"sz000837", name:"秦川机床", segments:["rv", "screw"],
      origin:"domestic", listed:{ status:"listed", code:"000837.SZ" }, tier:"head",
      one_liner:"依托机床、磨齿和精密制造能力开发机器人关节减速器，布局RV减速器产业化。",
      position:"国产RV早期重要玩家，优势在母机和加工工艺积累，竞争焦点是规模化交付和客户验证。",
      source_type:"primary", confidence:"high",
      source:"秦川机床年度报告及交易所互动易中关于机器人关节减速器/RV减速器业务披露。" },
    { id:"u05", name:"南通振康 ZKRV", segments:["rv"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"waist",
      one_liner:"专注机器人RV减速器研发制造，产品用于工业机器人关节及自动化装备。",
      position:"非上市国产专业厂商代表，在机器人RV细分较聚焦，但公开财务和大客户验证信息少于A股公司。",
      source_type:"primary", confidence:"medium",
      source:"南通振康机械有限公司官网ZKRV/RV减速器产品资料。" },
    { id:"sh603915", name:"国茂股份", segments:["rv"],
      origin:"domestic", listed:{ status:"listed", code:"603915.SH" }, tier:"waist",
      one_liner:"传统通用减速机龙头，延伸布局机器人精密减速器，涵盖RV等精密传动产品。",
      position:"制造规模和渠道能力强，但在高端机器人RV减速器的产业化地位仍低于双环、秦川等先发玩家。",
      source_type:"primary", confidence:"medium",
      source:"国茂股份年度报告及公司关于精密减速器/机器人减速器业务的公告披露。" },
    { id:"sz300580", name:"贝斯特/宇华精机", segments:["screw"],
      origin:"domestic", listed:{ status:"listed", code:"300580.SZ" }, tier:"head",
      one_liner:"通过子公司布局高精度滚珠/滚柱丝杠、直线导轨和机器人线性执行器相关精密传动部件。",
      position:"A股中机器人行星滚柱丝杠预期最集中的国产替代标的之一，优势在精密加工和资本开支推进，量产验证仍是关键。",
      source_type:"primary", confidence:"high",
      source:"贝斯特2024年年度报告、互动易关于宇华精机高精度滚珠/滚柱丝杠及机器人业务答复，https://www.cninfo.com.cn" },
    { id:"sh601100", name:"恒立液压", segments:["screw"],
      origin:"domestic", listed:{ status:"listed", code:"601100.SH" }, tier:"head",
      one_liner:"由液压执行器龙头延伸至电动缸、滚柱丝杠、伺服电缸等机电执行器方向。",
      position:"工艺、制造和客户资源强，若人形机器人线性执行器放量，有望成为从液压向电动执行器迁移的头部国产玩家。",
      source_type:"primary", confidence:"medium",
      source:"恒立液压2024年年度报告及上交所E互动关于滚柱丝杠/电动缸业务答复，https://www.sse.com.cn / https://sns.sseinfo.com" },
    { id:"bj873593", name:"鼎智科技", segments:["screw", "coreless"],
      origin:"domestic", listed:{ status:"listed", code:"873593.BJ" }, tier:"waist",
      one_liner:"主营微特电机、丝杆步进电机、线性执行器，并披露布局人形机器人用空心杯电机、无框力矩电机及滚柱丝杠相关产品。",
      position:"更偏小型电机+线性执行器集成，具备进入机器人线性关节模组的弹性，但滚柱丝杠产业化规模需继续验证。",
      source_type:"primary", confidence:"medium",
      source:"鼎智科技2024年年度报告、北交所公告及投资者关系活动记录，https://www.bse.cn / https://www.cninfo.com.cn" },
    { id:"u10", name:"南京工艺装备制造有限公司", segments:["screw"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"国内老牌滚动功能部件厂商，产品覆盖滚珠丝杠、滚动导轨及高端精密传动部件，具备滚柱丝杠相关技术储备。",
      position:"非上市国产老牌供给侧代表，优势在传统精密丝杠产业化经验；机器人客户和资本市场透明度低于上市公司。",
      source_type:"primary", confidence:"medium",
      source:"南京工艺装备制造有限公司官网产品与公司介绍，http://www.njgy.com" },
    { id:"sh603667", name:"五洲新春", segments:["screw"],
      origin:"domestic", listed:{ status:"listed", code:"603667.SH" }, tier:"waist",
      one_liner:"从轴承套圈、精密零部件切入机器人滚柱丝杠相关滚柱、丝杠支承轴承等关键零件。",
      position:"更偏行星滚柱丝杠上游零部件而非完整丝杠副，受益于国产滚柱丝杠放量但议价位置弱于总成厂。",
      source_type:"primary", confidence:"medium",
      source:"五洲新春2024年年度报告、上交所E互动关于机器人滚柱丝杠零部件进展答复，https://www.sse.com.cn / https://sns.sseinfo.com" },
    { id:"u12", name:"Ewellix/SKF Motion Technologies（现Schaeffler）", segments:["screw"],
      origin:"overseas", listed:{ status:"acquired", code:"" }, tier:"head",
      one_liner:"全球线性运动与电动执行器供应商，产品覆盖行星滚柱丝杠、滚珠丝杠和高性能线性执行器。",
      position:"海外对标龙头之一，技术和应用验证领先，是国产替代在寿命、效率、噪声和一致性上追赶的主要标杆。",
      source_type:"primary", confidence:"high",
      source:"Ewellix官方roller screws产品页及Schaeffler收购Ewellix公告，https://www.ewellix.com / https://www.schaeffler.com" },
    { id:"u13", name:"Rollvis SA", segments:["screw"],
      origin:"overseas", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"瑞士专业滚柱丝杠厂商，提供标准、反向、循环等多类型行星滚柱丝杠。",
      position:"细分技术标杆型海外玩家，产品谱系完整、精度和寿命口碑强，是国产厂商在高端小型化场景的对照系。",
      source_type:"primary", confidence:"high",
      source:"Rollvis官方产品页，https://www.rollvis.com" },
    { id:"sh688160", name:"步科股份", segments:["frameless"],
      origin:"domestic", listed:{ status:"listed", code:"688160.SH" }, tier:"head",
      one_liner:"工业自动化与机器人运动控制厂商，布局低压伺服、无框力矩电机、空心杯电机等机器人关节动力与驱控产品。",
      position:"A股中机器人电机与低压伺服代表性国产替代标的，强项在小型化伺服和机器人客户导入。",
      source_type:"primary", confidence:"high",
      source:"https://www.kinco.cn/ ; https://www.sse.com.cn/assortment/stock/list/info/announcement/index.shtml?productId=688160" },
    { id:"sh688320", name:"禾川科技", segments:["frameless", "encoder"],
      origin:"domestic", listed:{ status:"listed", code:"688320.SH" }, tier:"head",
      one_liner:"伺服系统及工业自动化核心部件厂商，面向人形机器人布局无框力矩电机、空心杯电机、编码器、驱动器等部件。",
      position:"伺服平台能力完整，具备从工业伺服迁移到机器人关节动力源的国产替代潜力。",
      source_type:"primary", confidence:"high",
      source:"https://www.hc-system.com/ ; https://www.sse.com.cn/assortment/stock/list/info/announcement/index.shtml?productId=688320" },
    { id:"sz002979", name:"雷赛智能", segments:["frameless"],
      origin:"domestic", listed:{ status:"listed", code:"002979.SZ" }, tier:"waist",
      one_liner:"运动控制和伺服驱动厂商，产品覆盖伺服、步进、控制器，并推进机器人用无框电机及关节模组相关产品。",
      position:"渠道和驱控积累较强，切入无框电机属于国产运动控制厂商向人形关节扩品类路径。",
      source_type:"primary", confidence:"medium",
      source:"https://www.leisai.com/ ; https://www.szse.cn/disclosure/listed/notice/index.html?stock=002979" },
    { id:"sh603728", name:"鸣志电器", segments:["frameless", "coreless"],
      origin:"domestic", listed:{ status:"listed", code:"603728.SH" }, tier:"waist",
      one_liner:"控制电机及驱动系统厂商，产品线覆盖无刷电机、伺服电机、空心杯电机、无框类电机及驱动控制。",
      position:"小型精密电机基础较深，适合灵巧手、轻量关节等场景；主关节高扭矩密度份额仍需客户验证。",
      source_type:"primary", confidence:"medium",
      source:"https://www.moonsindustries.com.cn/ ; https://www.sse.com.cn/assortment/stock/list/info/announcement/index.shtml?productId=603728" },
    { id:"u18", name:"T-MOTOR/CubeMars 奇翼电机", segments:["frameless"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"waist",
      one_liner:"提供机器人关节电机、无刷无框电机和一体化执行器，产品用于四足、人形、外骨骼及科研机器人。",
      position:"国产非上市专业机器人电机供应商，产品工程化和开发者生态较强，是中小批量机器人关节国产化的重要玩家。",
      source_type:"primary", confidence:"medium",
      source:"https://www.cubemars.com/ ; https://store.tmotor.com/" },
    { id:"xphn", name:"派克汉尼汾 Parker Hannifin", segments:["frameless"],
      origin:"overseas", listed:{ status:"listed", code:"PH.N" }, tier:"head",
      one_liner:"全球运动控制厂商，提供K系列等无框伺服/力矩电机，面向机器人、协作机器人、AGV、医疗等紧凑直驱应用。",
      position:"海外高端无框电机标杆之一，在可靠性、扭矩密度和全球客户验证上是国产替代对标对象。",
      source_type:"primary", confidence:"high",
      source:"https://www.parker.com/us/en/product-list/frameless-servo-motors" },
    { id:"u20", name:"科尔摩根 Kollmorgen", segments:["frameless"],
      origin:"overseas", listed:{ status:"subsidiary", code:"" }, tier:"head",
      one_liner:"全球运动控制厂商，TBM/TBM2G等无框伺服电机用于机器人关节、协作机器人、外骨骼等高功率密度场景。",
      position:"国际无框力矩电机核心标杆，产品系列和机器人场景验证成熟，是国产厂商技术对标对象。",
      source_type:"primary", confidence:"high",
      source:"https://www.kollmorgen.com/en-us/products/motors/servo/frameless" },
    { id:"xalnto", name:"Allient/Allied Motion", segments:["frameless"],
      origin:"overseas", listed:{ status:"listed", code:"ALNT.O" }, tier:"head",
      one_liner:"精密运动控制厂商，提供Quantum系列无框力矩电机和定制化电机，应用于机器人、医疗、航空航天等场景。",
      position:"海外专业运动控制供应商，在定制无框电机和高性能客户认证方面具备先发优势。",
      source_type:"primary", confidence:"high",
      source:"https://www.allient.com/products/motors/frameless-torque-motors/" },
    { id:"sz002139", name:"拓邦股份", segments:["coreless"],
      origin:"domestic", listed:{ status:"listed", code:"002139.SZ" }, tier:"waist",
      one_liner:"智能控制器龙头，布局空心杯电机、电控和机器人执行器相关方案。",
      position:"优势在控制器、电机驱动和客户资源，空心杯电机更多体现为机电控一体化延伸，单体电机头部属性弱于鸣志/鼎智。",
      source_type:"primary", confidence:"medium",
      source:"深交所/公司公告：拓邦股份2024年年度报告、投资者关系活动记录表。" },
    { id:"sh688698", name:"伟创电气", segments:["coreless"],
      origin:"domestic", listed:{ status:"listed", code:"688698.SH" }, tier:"waist",
      one_liner:"工业自动化与运动控制企业，围绕人形机器人布局空心杯电机、无框力矩电机、驱动器等部件。",
      position:"从伺服/变频控制向机器人执行部件扩展，具备系统集成协同，但空心杯量产验证仍处爬坡期。",
      source_type:"primary", confidence:"medium",
      source:"上海证券交易所/公司公告：伟创电气2024年年度报告、投资者关系活动记录表。" },
    { id:"u24", name:"万至达电机（Wanzhida Motor）", segments:["coreless"],
      origin:"jv", listed:{ status:"unlisted", code:"" }, tier:"waist",
      one_liner:"生产空心杯电机、无刷电机、齿轮箱电机等微型驱动产品，覆盖医疗、自动化、消费电子等小型高响应场景。",
      position:"偏中小功率微电机制造商，可作为国产供应链补充；机器人灵巧手公开定点和高端品牌替代证据弱于上市龙头。",
      source_type:"primary", confidence:"medium",
      source:"万至达电机官网：公司简介及空心杯/无刷微型电机产品页。" },
    { id:"u25", name:"Maxon（麦克森）", segments:["coreless"],
      origin:"overseas", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"瑞士高端精密驱动厂商，提供有刷/无刷空心杯直流电机、编码器、减速箱和控制器。",
      position:"全球空心杯电机标杆，机器人灵巧手高性能样机常用参考对象，是国产替代的主要对标。",
      source_type:"primary", confidence:"high",
      source:"Maxon官网：DCX/ECX系列空心杯绕组电机、机器人驱动系统产品资料。" },
    { id:"u26", name:"Faulhaber（冯哈伯）", segments:["coreless"],
      origin:"overseas", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"德国精密微驱动厂商，提供无铁芯直流微电机、无刷电机、减速器、编码器和控制器。",
      position:"高端微型运动控制标杆，优势在寿命、效率和定制化能力，是国产厂商追赶的核心海外参照。",
      source_type:"primary", confidence:"high",
      source:"Faulhaber官网：DC-Micromotors、brushless DC-servomotors及机器人/医疗应用资料。" },
    { id:"u27", name:"Portescap", segments:["coreless"],
      origin:"overseas", listed:{ status:"subsidiary", code:"" }, tier:"head",
      one_liner:"精密微电机品牌，提供Athlonix空心杯直流电机、无刷电机、步进电机和减速电机。",
      position:"全球医疗和工业微驱动强势玩家，空心杯产品线成熟；在中国机器人供应链中更多是高端进口替代对象。",
      source_type:"primary", confidence:"high",
      source:"Portescap官网：Athlonix coreless DC motors、robotics/medical miniature motor application资料；Regal Rexnord品牌资料。" },
    { id:"sz002338", name:"长春禹衡光学有限公司（奥普光电子公司）", segments:["encoder"],
      origin:"domestic", listed:{ status:"subsidiary", code:"002338.SZ" }, tier:"head",
      one_liner:"国内光电编码器老牌厂商，覆盖增量式、绝对式旋转编码器及光栅测量产品。",
      position:"国产光电编码器最核心的替代标的之一，对标海德汉/雷尼绍的高精度测量链条，但在顶级精度、批量一致性和高端协议生态上仍需追赶。",
      source_type:"primary", confidence:"medium",
      source:"巨潮资讯网：奥普光电年度报告/信息披露；公司官网/禹衡光学产品资料，https://www.cninfo.com.cn/ ，http://www.up-china.com/" },
    { id:"sz300503", name:"广州昊志机电股份有限公司", segments:["encoder"],
      origin:"domestic", listed:{ status:"listed", code:"300503.SZ" }, tier:"waist",
      one_liner:"高端装备功能部件厂商，机器人业务覆盖谐波减速器、无框力矩电机、编码器、驱动器等关节核心部件。",
      position:"定位是一体化关节部件平台，编码器与电机/减速器协同价值高；单独编码器外供与高端精度验证仍弱于专业测量厂商。",
      source_type:"primary", confidence:"medium",
      source:"巨潮资讯网：昊志机电年度报告/投资者关系公告，https://www.cninfo.com.cn/new/disclosure/stock?stockCode=300503" },
    { id:"sz300124", name:"汇川技术股份有限公司", segments:["encoder"],
      origin:"domestic", listed:{ status:"listed", code:"300124.SZ" }, tier:"head",
      one_liner:"国内工业自动化龙头，伺服驱动、伺服电机、控制器和工业机器人产品体系完整。",
      position:"编码器不是独立主业，但其伺服系统规模和客户基础决定其可推动国产反馈器件导入，是下游集成牵引型玩家。",
      source_type:"primary", confidence:"medium",
      source:"汇川技术官网产品导航及年度报告，https://www.inovance.com/ ，https://www.cninfo.com.cn/new/disclosure/stock?stockCode=300124" },
    { id:"u31", name:"上海精浦机电有限公司（GEMPLE）", segments:["encoder"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"waist",
      one_liner:"工业编码器厂商，产品覆盖增量式、绝对值、多圈、拉线及防爆编码器等。",
      position:"在通用工业场景具备国产替代性价比优势，但面向人形机器人薄型高精度关节编码器的公开验证较少。",
      source_type:"secondary", confidence:"low",
      source:"公司产品资料及行业公开资料交叉核验；官网入口以公司公开产品页为准。" },
    { id:"u32", name:"海德汉 HEIDENHAIN", segments:["encoder"],
      origin:"overseas", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"德国高精度测量系统龙头，提供角度编码器、旋转编码器、直线光栅尺和数控系统。",
      position:"全球高端光电编码器标杆，角度测量精度可到角秒级，是国产高端编码器主要追赶对象。",
      source_type:"primary", confidence:"high",
      source:"HEIDENHAIN angle encoders official page, https://www.heidenhain.com/products/encoders/angle-encoders" },
    { id:"xlsersw", name:"雷尼绍 Renishaw plc", segments:["encoder"],
      origin:"overseas", listed:{ status:"listed", code:"LSE:RSW" }, tier:"head",
      one_liner:"英国精密测量与运动控制公司，提供开放式/封闭式光学编码器、电感编码器、磁编码器和激光编码器。",
      position:"在高端光学开放式编码器、读头和栅尺生态中领先，是高精度机器人、半导体和机床运动控制的重要海外参考。",
      source_type:"primary", confidence:"high",
      source:"Renishaw official product navigation: Position and motion control / optical, inductive, magnetic and laser encoders, https://www.renishaw.com/" },
    { id:"u34", name:"多摩川精机 Tamagawa Seiki / 多摩川精密电机（苏州）", segments:["encoder"],
      origin:"jv", listed:{ status:"subsidiary", code:"" }, tier:"head",
      one_liner:"日本多摩川体系在华平台，母公司产品覆盖旋转编码器、旋变/同步器、伺服电机与驱动器。",
      position:"磁编码器/旋变和伺服反馈领域的日系强势供应商，在机器人关节反馈中具备成熟可靠性；国产替代主要围绕磁编码器芯片、旋变和薄型绝对值方案展开。",
      source_type:"primary", confidence:"medium",
      source:"Tamagawa Seiki official products page, https://www.tamagawa-seiki.com/" },
    { id:"sh603662", name:"柯力传感", segments:["fts"],
      origin:"domestic", listed:{ status:"listed", code:"603662.SH" }, tier:"head",
      one_liner:"A股传感器龙头，官网披露机器人传感器包含六轴力、三轴力、关节力矩和微型力传感器系列。",
      position:"具备上市公司资金、制造和客户基础，是国产替代中从称重/工业传感向机器人全身传感器扩张的代表。",
      source_type:"primary", confidence:"high",
      source:"https://www.kelichina.com/index.html" },
    { id:"u36", name:"常州坤维传感科技有限公司", segments:["fts"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"专注高性能力学类传感器及力控解决方案，产品中心覆盖常规/防爆/高性能六维力传感器、关节扭矩传感器等。",
      position:"国产六维力传感器代表性专精厂商，官网展示智元、银河通用、北京人形机器人、优必选等机器人客户/伙伴，国产替代相关性强。",
      source_type:"primary", confidence:"high",
      source:"https://www.kunweitech.com/" },
    { id:"u37", name:"深圳市鑫精诚传感技术有限公司（XJCSENSOR）", segments:["fts"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"waist",
      one_liner:"力传感器厂商，官网机器人应用覆盖协作末端、机器人关节、灵巧手、腕部和踝部，并列示多款6-Axis Force Sensor。",
      position:"产品线丰富、工程交付导向强，在机器人六维力/小型力传感器国产替代中偏腰部供应商。",
      source_type:"primary", confidence:"high",
      source:"https://www.xjcsensor.com/" },
    { id:"u38", name:"帕西尼感知科技（PaXini）", segments:["fts"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"startup",
      one_liner:"围绕全身力学套件、多维触觉灵巧手和多维触觉人形机器人构建触觉感知产品生态。",
      position:"更偏具身智能触觉与灵巧手方案，区别于传统六轴力传感器厂商，是国产触觉传感器创业公司代表。",
      source_type:"primary", confidence:"high",
      source:"https://www.paxini.com/cn/" },
    { id:"u39", name:"ATI Industrial Automation", segments:["fts"],
      origin:"overseas", listed:{ status:"acquired", code:"" }, tier:"head",
      one_liner:"美国机器人末端六维力/力矩传感器标杆，官网列示Nano、Mini、Gamma、Delta、Omega、Axia等F/T型号。",
      position:"全球高端六维力传感器基准，国产玩家通常以其精度、可靠性和生态作为替代目标；公司已被Novanta收购。",
      source_type:"primary", confidence:"high",
      source:"https://www.ati-ia.com/products/ft/ft_ModelListing.aspx" },
    { id:"u40", name:"Nitta Corporation（ニッタ）", segments:["fts"],
      origin:"overseas", listed:{ status:"listed", code:"" }, tier:"waist",
      one_liner:"日本压力分布/薄膜触觉测量系统厂商，官网披露I-SCAN、HIGH SPEED I-SCAN、握持压力分布传感片等产品，并覆盖机器人手把持压力测量场景。",
      position:"海外触觉/压力分布参考厂商，更多是触觉阵列和压力分布测量基准，不是国产六轴力直接替代对象。",
      source_type:"primary", confidence:"high",
      source:"https://www.nitta.co.jp/product/sensor/" },
    { id:"u41", name:"Bota Systems", segments:["fts"],
      origin:"overseas", listed:{ status:"unlisted", code:"" }, tier:"waist",
      one_liner:"瑞士6轴力/力矩传感器厂商，产品面向机器人、自动化和Physical AI，覆盖MiniONE、Rokubi、SensONE等系列。",
      position:"新一代机器人六维力传感器海外竞争者，强调内置电子、低漂移、轻量化和ROS/EtherCAT生态，对国产厂商形成技术参照。",
      source_type:"primary", confidence:"high",
      source:"https://botasys.com/force-torque-sensors/" },
    { id:"u42", name:"因时机器人 Inspire Robots", segments:["hand"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"专注微型精密运动执行器和灵巧操作末端执行器，产品包括仿人五指灵巧手、微型伺服电缸及力控版本。",
      position:"国产灵巧手量产代表，公司官网称其为中国首款商业化量产五指灵巧手缔造者、灵巧手交付量超万台，已进入多家头部机器人企业。",
      source_type:"primary", confidence:"high",
      source:"https://www.inspire-robots.com/about%20us/profile/" },
    { id:"u43", name:"灵心巧手 LinkerBot", segments:["hand"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"聚焦五指仿人灵巧手硬件，面向人形机器人、科研和制造场景，强调低成本与规模化交付。",
      position:"新一代国产降本派龙头之一，WIRED称其2025年出货1万只手、价格低至约600美元，并正探索港股上市。",
      source_type:"secondary", confidence:"medium",
      source:"https://www.wired.com/story/made-in-china-the-dollar6-billion-chinese-startup-making-hands-for-humanoids/" },
    { id:"u44", name:"无际科技 WUJI Technology", segments:["hand"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"startup",
      one_liner:"深圳灵巧手创业公司，围绕机器人手、遥操作和数据采集工具链布局；学术论文中已有20-DoF WUJI Hand用于Unitree G1操作实验。",
      position:"更偏高自由度与数据采集/训练闭环，代表国产创业公司从硬件走向“手+遥操作+学习数据”的路线。",
      source_type:"secondary", confidence:"medium",
      source:"https://www.theguardian.com/technology/ng-interactive/2026/jul/06/china-dextrous-robotic-hands-humanoid ; https://arxiv.org/abs/2606.23680" },
    { id:"u45", name:"强脑科技 BrainCo", segments:["hand"],
      origin:"domestic", listed:{ status:"unlisted", code:"" }, tier:"waist",
      one_liner:"以非侵入式脑机接口和智能仿生手起家，产品包括智能仿生手、智能仿生腿等。",
      position:"严格说更接近仿生义肢/人机接口而非通用机器人灵巧手总成，但其多指驱动、感知和控制技术对国产灵巧手有迁移价值。",
      source_type:"secondary", confidence:"medium",
      source:"https://zh.wikipedia.org/wiki/%E5%BC%BA%E8%84%91%E7%A7%91%E6%8A%80" },
    { id:"u46", name:"Shadow Robot Company / Shadow Dexterous Hand", segments:["hand"],
      origin:"overseas", listed:{ status:"unlisted", code:"" }, tier:"head",
      one_liner:"英国Shadow Robot提供五指Shadow Dexterous Hand，20个驱动自由度、24关节、腱驱动，并可选多种触觉指尖。",
      position:"海外高端研究型标杆，精度、传感与ROS生态领先，但成本与量产属性弱，是国产替代对标上限。",
      source_type:"primary", confidence:"high",
      source:"https://www.shadowrobot.com/dexterous-hand-series/" },
    { id:"u47", name:"Wonik Robotics / Allegro Hand", segments:["hand"],
      origin:"overseas", listed:{ status:"subsidiary", code:"" }, tier:"head",
      one_liner:"韩国Wonik Robotics旗下Allegro Hand提供V5 Sense、V5 Plus等多指机器人手，覆盖16-DOF结构、压力/触觉传感版本。",
      position:"全球科研与算法验证常用平台，结构紧凑、生态成熟；国产玩家主要在价格、交付和本土机器人客户适配上替代。",
      source_type:"primary", confidence:"high",
      source:"https://www.allegrohand.com/" },
  ],

  edges: [
    /* 竞争关系自动派生；此处仅留公开可溯的股权/供应关系（暂无）。 */
  ]
};
